-- me.config.ui

return {
  icons = {
    lsp = {
      kinds = {
        Array = "",
        Boolean = "",
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "",
        Interface = "",
        Key = "",
        Keyword = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "ﳠ",
        Number = "",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
      },
      diagnostic = {
        Error = " ",
        Hint = " ",
        Info = " ",
        Warn = " ",
      },
    },
    ui = {
      BigCircle = "",
      BigUnfilledCircle = "",
      BookMark = "",
      Bug = "",
      Calendar = "",
      Check = "",
      ChevronRight = "",
      Circle = "",
      Close = "",
      Code = "",
      Comment = "",
      Dashboard = "",
      Fire = "",
      Gear = "",
      History = "",
      Lightbulb = "",
      List = "",
      Lock = "",
      NewFile = "",
      Note = "",
      Package = "",
      Pencil = "",
      Project = "",
      Search = "",
      SignIn = "",
      Table = "",
      Telescope = "",
    },
    misc = {
      block = "█",
      circle = "●",
      ghost = "",
      github_icon = " ﯙ ",
      robot = "ﮧ",
      squirrel = "",
      tag = "",
      watch = "",
    },
    documents = {
      closed_folder = "",
      file = "",
      files = "",
      folder = "",
      open_folder = " ",
    },
    buftype = {
      neotree = " ",
      lazy = " ",
      telescope = " ",
      vista = "Ξ ",
    },
    bar = {
      a = "┃",
      b = "│",
      c = "│",
      d = "▏",
      f = "│",
      g = "¦",
      h = "┊",
      i = "▏",
      j = "│",
    },
  },
}
